"""creating counter table

Revision ID: 70acc94421a3
Revises: 
Create Date: 2022-02-15 10:18:32.308182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70acc94421a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('counter')
    # ### end Alembic commands ###
